version: '3.8'

services:
  # Fuentes Estáticas
  fuente-estatica:
    build:
      context: ./apps/fuentes/estatica
      dockerfile: Dockerfile
    ports:
      - "7001:7001"
    container_name: metamapa-fuente-estatica
    restart: unless-stopped
    environment:
      - DAO_TYPE=filesystem
      - PROCESSOR_TYPE=csv
      - DATA_URL=src/main/resources/data/desastres_naturales_argentina.csv
    networks:
      - metamapa-network

  # Fuentes Dinámicas
  fuente-dinamica:
    build:
      context: ./apps/fuentes/dinamica
      dockerfile: Dockerfile
    ports:
      - "7002:7002"
    container_name: metamapa-fuente-dinamica
    restart: unless-stopped
    networks:
      - metamapa-network

  # Proxy MetaMapa
  fuente-proxy-metamapa:
    build:
      context: ./apps/fuentes/proxy/metamapa
      dockerfile: Dockerfile
    ports:
      - "7003:7003"
    container_name: metamapa-fuente-proxy-metamapa
    restart: unless-stopped
    networks:
      - metamapa-network

  # Proxy Demo
  fuente-proxy-demo:
    build:
      context: ./apps/fuentes/proxy/demo
      dockerfile: Dockerfile
    ports:
      - "7004:7004"
    container_name: metamapa-fuente-proxy-demo
    restart: unless-stopped
    networks:
      - metamapa-network

  # Agregador
  agregador:
    build:
      context: ./apps/agregador
      dockerfile: Dockerfile
    ports:
      - "7005:7005"
    container_name: metamapa-agregador
    restart: unless-stopped
    networks:
      - metamapa-network

  # MetaMapa
  metamapa:
    build:
      context: ./apps/metamapa
      dockerfile: Dockerfile
    ports:
      - "7006:7006"
    container_name: metamapa-administrativo
    restart: unless-stopped
    networks:
      - metamapa-network

  # Prometheus
  metric-collector:
    image: prom/prometheus:latest
    container_name: metric-collector
    volumes:
      - ./apps/estadisticas/metric-collector/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - agregador
      - metamapa
    networks:
      - metamapa-network

  # Alertmanager
  gestor-alertas:
    image: prom/alertmanager:latest
    container_name: gestor-alertas
    volumes:
      - ./apps/estadisticas/gestor-alertas/config.yml:/etc/alertmanager/config.yml
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    ports:
      - "9093:9093"
    depends_on:
      - metric-collector
    networks:
      - metamapa-network

  # Grafana
  dashboard-visualizador:
    image: grafana/grafana:latest
    container_name: dashboard-visualizador
    ports:
      - "3000:3000"
    volumes:
      - ./apps/estadisticas/dashboard-visualizador/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./apps/estadisticas/dashboard-visualizador/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./apps/estadisticas/dashboard-visualizador/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - metric-collector
    networks:
      - metamapa-network

networks:
  metamapa-network:
    driver: bridge 