global:
  resolve_timeout: 5m

route:
  receiver: 'proxy-metamapa'
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h

receivers:
  - name: 'proxy-metamapa'
    webhook_configs:
      - url: 'http://proxy-metamapa:7003/consenso'
        send_resolved: true 