name: Maven Build

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Iniciar repo
        uses: actions/checkout@v3

      - name: ☕ Instalar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: 📂 Maven build
        working-directory: MetaMapa
        run: mvn -B clean verify
