name: Maven Tests

on:
  push: # Se ejecuta en cada push
    branches: ["**"] # Todas las ramas
  pull_request: # También en PRs a cualquier rama
    branches: ["**"]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Clonar el repositorio
        uses: actions/checkout@v3

      - name: ☕ Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: 🧪 Ejecutar tests con Maven
        working-directory: MetaMapa/test
        run: mvn -B clean test
